name: DragonWings
version: 1.0
description: Allows the managing of flight based on factions and their territories
author: FlameKnight15
main: com.chivalrycraft.Core
depend: [Factions]

commands:
   fly:
      description: Alias
      usage: /fly <player>
      aliases: [fly]
   ground:
      description: Send a player to the ground!
      usage: /ground <player>
   flypart:
      description: Toggles the fly particles of a player or yourself
      usage: /flypart <name>
